version: 0.0.0-ci-{build}

image:
  - Visual Studio 2022

branches:
  only:
    - master
    - master-v8
    - /\d+\.\d+\.\d+/

pull_requests:
  do_not_increment_build_number: false

skip_branch_with_pr: true

configuration: Release

shallow_clone: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

skip_commits:
  files:
    - "**/*.md"
    - .gitignore
    - .editorconfig
    - samples/**/*
  message: /.*skip\sci.*/

init:
  - cmd: dotnet --version

  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          try {
              Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME
          }
          catch {
              Write-Host "Failed to update build version from tag."
              Write-Host $_.Exception.Message
          }
      }

  - ps: |
      Write-Host "APPVEYOR_BUILD_VERSION = '$env:APPVEYOR_BUILD_VERSION'"
      Write-Host "APPVEYOR_REPO_TAG_NAME = '$env:APPVEYOR_REPO_TAG_NAME'"
      Write-Host "Pull Request = '$env:APPVEYOR_PULL_REQUEST_NUMBER'"

  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet tool update -g dotnet-sonarscanner
          if ($LASTEXITCODE -ne 0) {
              dotnet tool install -g dotnet-sonarscanner
          }
      }

  - ps: |
      dotnet tool update -g minicover
      if ($LASTEXITCODE -ne 0) {
          dotnet tool install -g minicover
      }

nuget:
  project_feed: true

before_build:
  - dotnet restore

build_script:

  - cmd: set JAVA_HOME=C:\Program Files\Java\jdk25
  - cmd: if not exist "%JAVA_HOME%\bin\java.exe" exit /b 1
  - cmd: set PATH=%JAVA_HOME%\bin;%PATH%

  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {

          if ([string]::IsNullOrWhiteSpace($env:SONAR_TOKEN)) {
              throw "SONAR_TOKEN environment variable is missing."
          }

          dotnet sonarscanner begin `
            /k:"adrianiftode_FluentAssertions.Web" `
            /o:"adrianiftode-github" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.token="$env:SONAR_TOKEN" `
            /v:"$env:APPVEYOR_BUILD_NUMBER" `
            /d:sonar.cs.opencover.reportsPaths="opencovercoverage.xml" `
            /d:sonar.coverage.exclusions="test/**"

          if ($LASTEXITCODE -ne 0) {
              throw "SonarScanner begin failed."
          }
      }

  - cmd: dotnet build -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION%

  - cmd: minicover instrument

test_script:
  - cmd: dotnet test --no-restore --no-build --nologo --verbosity:q

after_test:

  - cmd: minicover uninstrument

  - cmd: minicover opencoverreport

  - cmd: minicover report --threshold 95

  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {

          dotnet sonarscanner end `
            /d:sonar.token="$env:SONAR_TOKEN"

          if ($LASTEXITCODE -ne 0) {
              throw "SonarScanner end failed."
          }
      }

  - cmd: dotnet pack --include-symbols -c %CONFIGURATION% /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: '**\FluentAssertions.Web*.nupkg'
    name: FluentAssertionsPackages

  - path: '**\AwesomeAssertions.Web*.nupkg'
    name: AwesomeAssertionsPackages

deploy:

  - provider: NuGet
    api_key:
      secure: 6rs63nhNUqswGZO+5fPTAErKVSWuK015FkhlxPHuodj5F2i8ii+Im156iTCi7p6I
    skip_symbols: true
    artifact: FluentAssertionsPackages
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: WXU/Xj3ntIZVx89KDAa/V/FGerV2fURqVQJxrKIqMcCijmXeC065twmHPYQMWGBabafs1llkLbe6DMKRAGnz+GxwH8GpT3A86rcSOLxbsp4uRkeMRsLxWHI+eDHTonOY
    artifact: FluentAssertionsPackages
    on:
      appveyor_repo_tag: true