<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);AAV;FA8</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="AwesomeAssertions.Analyzers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Assertions.Web\Assertions.Web.csproj" />
    <ProjectReference Include="..\..\src\Assertions.Web.Serializers.NewtonsoftJson\Assertions.Web.Serializers.NewtonsoftJson.csproj" />
    <ProjectReference Include="..\..\src\AwesomeAssertions.Web\AwesomeAssertions.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Assertions.Web.Serializers.NewtonsoftJson.Tests\**\*.*" Exclude="**\bin\**;**\obj\**;**\Properties\**;**\*.csproj">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

</Project>
