<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);SH</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Assertions.Core\Assertions.Core.csproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Assertions.Core\ISerializer.cs" Link="ISerializer.cs" />
    <Compile Include="..\Assertions.Core\DeserializationException.cs" Link="DeserializationException.cs" />
    <Compile Include="..\Assertions.Core\AssertionsWebConfig.cs" Link="AssertionsWebConfig.cs" />
    <Compile Include="..\Assertions.Core\SystemTextJsonSerializerConfig.cs" Link="SystemTextJsonSerializerConfig.cs" />
    <Compile Include="..\Assertions.Core\Internal\HttpContentExtensions.cs" Link="Internal\HttpContentExtensions.cs" />
    <Compile Include="..\Assertions.Core\Internal\Serializers\SystemTextJsonSerializer.cs" Link="Internal\Serializers\SystemTextJsonSerializer.cs" />
  </ItemGroup>

</Project>
