<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);SH</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shouldly.Web.Types\Shouldly.Web.Types.csproj" />
    <ProjectReference Include="..\..\src\Shouldly.Web\Shouldly.Web.csproj" />
    <ProjectReference Include="..\..\src\Shouldly.Web.Serializers.NewtonsoftJson\Shouldly.Web.Serializers.NewtonsoftJson.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\FluentAssertions.Web.Serializers.NewtonsoftJson.Tests\**\*.*" Exclude="**\bin\**;**\obj\**;**\Properties\**;**\*.csproj;**\ConfigureFluentAssertionsWebFixture.cs">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

</Project>
