<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Analyzers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FluentAssertions.HttpMessageFormatter\FluentAssertions.HttpMessageFormatter.csproj" />
  </ItemGroup>

</Project>
